//Constants for app
export const BLUE_SHIRT = "BLUE";
export const RED_SHIRT = "RED";
export const QUANTITY_CARD = [24, 36, 52];
export const QUANTITY_CARD24 = 24;
export const QUANTITY_CARD36 = 36;
export const QUANTITY_CARD52 = 52;
export const USER = "USER";
export const COMPUTER = "COMPUTER";

//GAME
export const START_GAME = "GAME/START_GAME";
export const STOP_GAME = "GAME/STOP_GAME";
export const RESTART_GAME = "GAME/RESTART_GAME";

//TABLE
export const SET_TRUMP_SUIT = "TABLE/SET_TRUMP_SUIT";
export const SET_CARD_KIT = "TABLE/SET_CARD_KIT";
export const SET_MOVE = "TABLE/SET_MOVE";
export const SET_CARDS_TABLE = "TABLE/SET_CARDS_TABLE";
export const SET_CARD_TABLE = "TABLE/SET_CARD_TABLE";
export const REMOVE_CARDS_TABLE = "TABLE/REMOVE_CARDS_TABLE";
export const SET_ADITION = "TABLE/SET_ADITION";

//SETTING
export const SHOW_SETTING = "SETTING/SHOW_SETTING";
export const HIDE_SETTING = "SETTING/HIDE_SETTING";
export const SET_QUANTITY_CARD = "SETTING/SET_QUANTITY_CARD";
export const SET_SHIRT_CARD = "SETTING/SET_SHIRT_CARD";

//USER
export const SET_MOVE_USER = "USER/SET_MOVE_USER";
export const SET_BEAT_USER = "USER/SET_BEAT_USER";
export const SET_TAKES_USER = "USER/SET_TAKES_USER";
export const SET_CARD_USER = "USER/SET_CARD_USER";
export const SET_CARDS_USER = "USER/SET_CARDS_USER";

//COMPUTER
export const SET_MOVE_COMPUTER = "COMPUTER/SET_MOVE_COMPUTER";
export const SET_CARD_COMP = "COMPUTER/SET_CARD_COMP";
export const SET_CARDS_COMP = "COMPUTER/SET_CARDS_COMP";
export const SET_BEAT_COMPUTER = "COMPUTER/BEAT_COMPUTER";
export const SET_TAKES_COMPUTER = "COMPUTER/TAKES_COMPUTER";
