//Constants for app
export const BLUE_SHIRT = 'BLUE';
export const RED_SHIRT = 'RED';
export const QUANTITY_CARD = [24,36,52];
export const QUANTITY_CARD24 = 24;
export const QUANTITY_CARD36 = 36;
export const QUANTITY_CARD52 = 52;

//GAME
export const START_GAME = 'GAME/START_GAME';
export const STOP_GAME = 'GAME/STOP_GAME';
export const RESTART_GAME = 'GAME/RESTART_GAME';
export const SET_TRUMP_SUIT = 'GAME/SET_TRUMP_SUIT';
export const SET_CARD_KIT = 'GAME/SET_CARD_KIT';
export const SET_CARD_COMP = 'GAME/SET_CARD_COMP';
export const SET_CARD_PLAYER = 'GAME/SET_CARD_PLAYER';
export const SET_MOVE = 'GAME/SET_MOVE';
export const BEAT_OFF_USER = 'GAME/BEAT_OFF_USER';
export const SET_CARDS_TABLE = 'GAME/SET_CARDS_TABLE';
export const SET_CARD_TABLE = 'GAME/SET_CARD_TABLE';
export const REMOVE_CARDS_TABLE = 'GAME/REMOVE_CARDS_TABLE';
export const BEAT_COMPUTER = 'GAME/BEAT_COMPUTER';

//SETTING
export const SHOW_SETTING = 'SETTING/SHOW_SETTING';
export const HIDE_SETTING = 'SETTING/HIDE_SETTING';
export const SET_QUANTITY_CARD = 'SETTING/SET_QUANTITY_CARD';
export const SET_SHIRT_CARD = 'SETTING/SET_SHIRT_CARD';
